### ISSUE TITLE
rpc: broken pipe error on Mesh when WS client exits

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#109]
While testing the Mesh JSON-RPC orders subscription endpoint, I've discovered a bug where if the client is force-killed (`ctrl-c` in terminal), the Mesh node emits the following error on an endless interval: 

```
{
    "error": "write tcp4 127.0.0.1:60557->127.0.0.1:57219: write: broken pipe",
    "level": "error",
    "msg": "error while calling notifier.Notify",
    "time": "2019-05-30T10:53:41+01:00"
}
```

Additional observations:
- Stops after 205 errors emitted
- Occuring intermittently

**Comment by albrow** [comment]
@fabioberger I can't reproduce this. Can you provide steps to reproduce?

I tried:

1. Run `ETHEREUM_NETWORK_ID="50" ETHEREUM_RPC_URL="http://localhost:8545" VERBOSITY=5 RPC_PORT=60147 DATABASE_DIR=/tmp/node0_db USE_BOOTSTRAP_LIST=true mesh`
2. In a separate terminal session, run `RPC_ADDRESS="ws://localhost:60147" ETHEREUM_RPC_URL="http://localhost:8545" go run cmd/demo/subscribe_to_orders/main.go`
3. In a separate terminal session run `RPC_ADDRESS="ws://localhost:60147" ETHEREUM_RPC_URL="http://localhost:8545" go run cmd/demo/add_order/main.go`
4. Kill the second terminal session with `ctrl+c`.

I didn't see any errors. I also tried with two Mesh nodes running simultaneously and sharing orders with one another.

**Comment by fabioberger** [comment]
@albrow I've just spent 5mins trying to cause the issue to re-appear and haven't succeeded so far. A bit strange since I don't think we've modified the code in question. My notes from the last time I was looking into this noted that:

- It occuring intermittently
- It stoped emitting the `write: broken pipe` error after ~205 errors were emitted

Let's keep this issue open for now, and I'll see if it re-appears in the next few days.

**Comment by fabioberger** [comment]
Update: Saw this bug again during testing using the `sra_bridge.go` script. I can confirm that it is an intermittent error. 

I added a log to the `err := <-rpcSub.Err()` select condition, and it returned:

```
{"err":"EOF","level":"error","msg":"rpcSub returned an error","time":"2019-06-06T09:09:48+01:00"}
```

After outputting X number of `write: broken pipe` errors.
