### ISSUE TITLE
Validate order schemas

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#131]
AFAICT, we don't currently do schema validations for orders received from peers (i.e., making sure they have the correct structure and all the required fields). We could use JSON Schemas for this. However, we will probably eventually switch to a more efficient encoding over the wire, in which case, some kind of schema validation that matches our encoding format would be preferred.

**Comment by fabioberger** [comment]
@albrow We already attempt unmarshalling the JSON payload into a`SignedOrder` struct.

1. That process will fail if the JSON is malformed
2. If it's proper JSON but has none of the required fields, the resultant `SignedOrder` will contain all the zero-values.
3. `BatchOffchainValidation` already validates that the `assetData` fields include parsable/supported `assetData` values and that the `Signature` includes a properly encoded 0x signature.

Thus the `BatchValidate()` method already reject orders that are malformed prior to any `eth_call`. Now we might want to validate for schema earlier simply to notify the developer that the JSON they are sending is not properly formatted. I'd be down to add it for this reason. Is this the reason you had in mind?

**Comment by fabioberger** [comment]
I'm open to adding support for this. Should we use JSON Schemas for now?

**Comment by albrow** [comment]
> Just to confirm that this is simply to warn developers who are sending an incorrect SignedOrder payload?

I was thinking it would reply to both orders received via RPC and orders received from peers.

> Should we use JSON Schemas for now? Or did you want to punt until we settle on a more efficient wire encoding?

Let's punt for now. If we use Protobufs there is already some built in schema validation if I understand correctly.

**Comment by fabioberger** [comment]
Decided to move forward with JSON schema validation for the Beta.
