### ISSUE TITLE
docker: Use CGO_ENABLED=1 in Dockerfile

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#138]
Since the Dockerfile is only used for server-side deployments and the cgo version of our dependencies are more performant then the non-cgo version, let's switch to compiling with cgo enabled when building the Docker image.

Perhaps we could use the `frolvlad/alpine-glibc` base image.

**Comment by opaolini** [comment]
If there is no specific requirement for `glibc`, then [alpine comes with musl]( https://alpinelinux.org/posts/Alpine-Linux-has-switched-to-musl-libc.html) , so we can stick here to the image we are already using.

PR -> https://github.com/0xProject/0x-mesh/pull/143
