### ISSUE TITLE
WIP: Telemetry Proposal

### ISSUE THREAD

**Issue by opaolini** [0xProject/0x-mesh#142]
Telemetry Spec Proposal
===

A mesh node would expose telemetry information, such as go runtime metrics / network / mesh specific information, that can be used to monitor its health and status.

## Minimum implementation

https://github.com/0xProject/0x-mesh/pull/141

## Exposing Metrics
To gather and expose those metrics it would use [Prometheus](https://prometheus.io) and its official [Go client library](https://prometheus.io/docs/guides/go-application/).

Those metrics instead of being pushed would be scraped from the node itself over HTTP.

Whether or not a running node will expose telemetry is configured via `ENV_VARS`:

```go
type Config struct {
...

	// RunTelemetry is whether to expose mesh metrics
	RunTelemetry bool `envvar:"RUN_TELEMETRY" default:"false"`

	// TelemetryPort is the port on which metrics are exposed
	// :<TelemetryPort>/metrics
	TelemetryPort int `envvar:"TELEMETRY_PORT" default:"3000"`
}

}
```

To add a custom metric, we first define it:
```go
package telemetry

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	AddOrdersRequests = promauto.NewCounter(prometheus.CounterOpts{
		Name: "mesh_jrpc_request_add_orders_total",
		Help: "The total number of mesh_addOrders JRPC requests",
	})

	AddPeerRequests = promauto.NewCounter(prometheus.CounterOpts{
		Name: "mesh_jrpc_request_add_peer_total",
		Help: "The total number of mesh_addPeer JRPC requests",
	})
)
```

And then invoke its method, in the case of `Counter` we *increase* it:

```go
// AddOrders calls rpcHandler.AddOrders and returns the validation results.
func (s *rpcService) AddOrders(orders []*zeroex.SignedOrder) (*zeroex.ValidationResults, error) {
	telemetry.AddOrdersRequests.Inc()
	return s.rpcHandler.AddOrders(orders)
}
```

Example Metrics pulled from the example implementation:
```
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 950272
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 7.25486e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 13
# HELP mesh_invalid_orders_seen The total number of invalid orders mesh has rejected via JSON RPC
# TYPE mesh_invalid_orders_seen counter
mesh_invalid_orders_seen 0
# HELP mesh_jrpc_request_add_orders_total The total number of mesh_addOrders JRPC requests
# TYPE mesh_jrpc_request_add_orders_total counter
mesh_jrpc_request_add_orders_total 173
# HELP mesh_jrpc_request_add_peer_total The total number of mesh_addPeer JRPC requests
# TYPE mesh_jrpc_request_add_peer_total counter
mesh_jrpc_request_add_peer_total 0
# HELP mesh_p2p_invalid_orders_seen The total number of invalid orders mesh has seen
# TYPE mesh_p2p_invalid_orders_seen counter
mesh_p2p_invalid_orders_seen 0
# HELP mesh_p2p_valid_orders_already_stored The total number of valid orders mesh has already stored and rejected via p2p
# TYPE mesh_p2p_valid_orders_already_stored counter
mesh_p2p_valid_orders_already_stored 0
# HELP mesh_p2p_valid_orders_seen The total number of valid orders mesh has seen
# TYPE mesh_p2p_valid_orders_seen counter
mesh_p2p_valid_orders_seen 0
# HELP mesh_valid_orders_seen The total number of valid orders mesh has accepted via JSON RPC
# TYPE mesh_valid_orders_seen counter
mesh_valid_orders_seen 0
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.14

```

The offical Go Library includes metrics surrounding the Go Runtime itself giving useful information like number of os threads created and garbage collection time.

## Consuming Metrics

The node running telemetry would expose metrics on: `http://localhost:<TELEMETRY_PORT>` which can then be scraped and consumed either by prometheus or simply ingested by a dashboard application.

Visualization can be easily done on [grafana](https://grafana.com/) or again, by a bespoke local dashboard application.

## Alerting

If the node will be monitored by Prometheus itself it would be trivial to add alert rules for some key metrics.

A basic `example`:

```yaml
alert: HighOrderRejectionRate
expr: sum(mesh_p2p_invalid_orders_seen[5m]) > 1000 
for: 1m
labels:
 severity: low
annotations:
 summary: High amount of rejected orders
 description: The node has rejected more than 1000 orders in the last 5 minutes
```

**TODO**
## Advantages of using Prometheus

* Easy to setup
* Plenty of support and dev tooling (Grafana, ...)
* Scalable to monitor a big cluster deployment
* Can be used to expose information to local dashboards
* Powerful functional query language makes it easy to select and aggregate time series data in real time -> https://prometheus.io/docs/prometheus/latest/querying/basics/

## Disadvantages
* Probably not useful for running in a `WASM` environment?
.

**Comment by albrow** [comment]
@opaolini does Prometheus support log aggregation? I have experience setting up an ELK stack (Elastisearch, Logstash, Kibana) for log aggregation and it does a lot of the same things that you mentioned here while also being more flexible.

**Comment by opaolini** [comment]
**Prometheus**: monitoring, metrics, metrics aggregation and alerts.
**Grafana**: Nice visualization dashboard for the above
**ELK**: log transportation via logstash/flutend, aggregation on elastichsearch and kibana for log visualization

Currently, Prometheus is usually deployed alongside an ELK/EFK stack, and I have used it in the past to monitor the ELK stack itself (especially an elasticsearch cluster)

It is true, that you could do some of the things by parsing the event data from logstash and later visualize them on kibana. Also it seems Elastic is getting more into the [metrics territory of observability](https://www.elastic.co/blog/observability-with-the-elastic-stack), introduced [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/6.6/metricbeat-modules.html) and embraced [Prometheus metrics standard](https://www.elastic.co/blog/elasticsearch-observability-embracing-prometheus-and-openmetrics-standards-for-metrics) 
   
However, ELK stack itself was not designed for time series data and metrics first in mind. 
   
All in all I think it is the question of what is exact purpose for implementing metrics/observability and how the instrumentation will be used.
   
As an example if you will be running a local simulation of a `mesh` network, I don't you'd want to spin up a an elastichsearch cluster (resource intensive) and then spend processing power parsing logs / events to grab the information like how many orders were rejected, or how many peers are connected. With the prometheus way and `pull` design, you simply grab that infromation from localhost `http://mesh-node-0:3000/metrics` , `http://localhost:3001/metrics`, ..etc  without ever needing to spin up `prometheus` itself.

Also if you will be operating the boostrap nodes on a `k8s` you will most likely be already running `prometheus` anyway :)
