### ISSUE TITLE
Automatically generate a private key in Docker image if needed

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#146]
The Docker image should generate a private key if needed. We need to do this in the entrypoint as opposed to in the image itself (otherwise everyone running the image would have the same key).

Alternatively we could include this functionality in the `mesh` executable so it automatically generates a new key and saves it in `PRIVATE_KEY_PATH` if there is none there.

**Comment by fabioberger** [comment]
I think it would be cleaner to have it be part of the `mesh` executable. That way, the entry point will remain as `ENTRYPOINT ./mesh`. Additionally, anyone who mounts an empty `0x_mesh` directory will have the PK be generated into it.
