### ISSUE TITLE
Investigate issues with using web3.js as an RPC client for Mesh

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#165]
@fabioberger and I have observed some issues when using web3.js as an RPC client for Mesh. Specifically, we have observed that sometimes an unexpected EOF error can occur when adding a large number of orders. The same issue does not appear with Go clients.

**Comment by dekz** [comment]
Chiming in on this. Experienced an issue when adding > 10 orders at a time. Batching in size 10 was successful. 

This was from hoovering all of Radar liquidity and throwing into Mesh.

**Comment by albrow** [comment]
> This was from hoovering all of Radar liquidity and throwing into Mesh.

Just wanted to point out that @fabioberger has a Node running which pipes Radar orders into Mesh using the Go client and we haven't had any issues there. I suspect that the client is at fault, either because it straight up has a bug or is doing something that is incompatible with our JSON RPC server.

**Comment by fabioberger** [comment]
Figure out what was causing the larger requests to fail and opened [an issue](https://github.com/theturtle32/WebSocket-Node/issues/359) with `websockets` to try and better understand whether this is expected behavior or a bug.
