### ISSUE TITLE
rpc: add configuration / status

### ISSUE THREAD

**Issue by dmvt** [0xProject/0x-mesh#201]
I'd like to be able to request the configuration and current status from an rpc endpoint. This would include:

- ethereum network id
- current block number / last block number received by mesh

**Comment by fabioberger** [comment]
Thanks for the suggestion @dmvt. I really like this idea. I've moved out your second suggestion into it's own PR: https://github.com/0xProject/0x-mesh/issues/202.

**Comment by fabioberger** [comment]
Thoughts on adding this @albrow?

**Comment by albrow** [comment]
@dmvt the [Ethereum network id is an environment variable](https://github.com/0xProject/0x-mesh/blob/master/DOCUMENTATION.md#possible-environment-variables) which is required during initialization. It's set by you and will never change unless you change it, so I think there is limited value in having an RPC endpoint for it.

An endpoint for getting the block number makes a lot more sense to me. Can you share more about your use case so we can determine how to prioritize this?

**Comment by dmvt** [comment]
Hey @albrow. I'd like to have the ability to confirm that Mesh and the regular ETH node connection are in sync programmatically. The network id being returned by Mesh would allow me to verify on startup that the application has not been directed to connect to a Mesh node on a different network than the RPC endpoint. Likewise, knowing the Mesh node's current block will allow the software to compare it against the RPC endpoint for the ETH node and verify that neither is behind the other (within a tolerance zone). In both cases, error states can trigger proactive notification to devops.

**Comment by albrow** [comment]
Makes sense. We could also have this endpoint return other information like how many peers you are currently connected to.

**Comment by dmvt** [comment]
That would be great. Any idea on ETA for this feature?

**Comment by albrow** [comment]
@dmvt we're focusing on tech debt and bug fixes at the moment. It would be next week at the earliest.

**Comment by fabioberger** [comment]
@dmvt working on this now.
