### ISSUE TITLE
rpc: Subscription endpoint for block events

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#202]
@dmvt would like to be able to subscribe to a 'blockNumber' topic which sends the current block number as it is updated.

Perhaps we should add a subscription endpoint that emits `meshdb.MiniHeaders` without logs. This would include the block number, hash and parentHash of the block and whether it's been added to/removed from the canonical chain.

**Comment by fabioberger** [comment]
Thoughts on adding this @albrow?

**Comment by albrow** [comment]
@fabioberger this makes a lot of sense to me. I'm just not sure how to balance it with our other priorities. It would help a lot to understand some real-world use cases.

**Comment by fabioberger** [comment]
@dmvt what use-case would you want to use this subscription for? Is it mostly a question of monitoring Mesh more closely and to make sure it's working as expected or are there other reasons for wanting to subscribe to blocks?

**Comment by albrow** [comment]
Closing this because the JSON-RPC API will be removed in v10. If we want to add support for this to the GraphQL API, we should create a new issue. However, it doesn't seem like there is much demand at the moment.
