### ISSUE TITLE
Use database transactions in blockwatch.Stack

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#208]
Some methods in `blockwatch.Stack` (e.g. [`Push`](https://github.com/0xProject/0x-mesh/blob/759101119189af3c3e737622c2b5920acbf1a7e4/ethereum/blockwatch/stack.go#L48)) require atomicity during read and write operations. This is currently accomplished by using a mutex, but could be made more efficient and safe by using database transactions.

**Comment by fabioberger** [comment]
This issue is outdated now that the stack no longer does any DB operations.
