### ISSUE TITLE
db: leveldb:closed and remains closed

### ISSUE THREAD

**Issue by dekz** [0xProject/0x-mesh#319]
`leveldb:closed` occurred and Mesh continued on operating without attempting a re-open or failing. All RPC connections remained open (though encountered -3200 errors). Upon restart everything operated successfully.

logs:
```
could not check if order was already stored
internal error in AddOrders RPC call leveldb:closed
```

<img width="614" alt="Screen Shot 2019-07-30 at 7 27 32 pm" src="https://user-images.githubusercontent.com/27389/62117924-2abe5780-b300-11e9-9759-4bb544b9be21.png">

[Kibana Logs](https://kibana.mesh.0x.org/app/kibana#/context/346670c0-a7ec-11e9-894c-399cdf4c7db3/docker/ow00QmwB-KIqeJ6CdSe5?_a=(columns:!(myPeerID,msg,error_string),filters:!(),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(pause:!f,value:43200000),time:(from:now-12h,mode:quick,to:now)))

**Comment by albrow** [comment]
I'm pretty sure this is already fixed by https://github.com/0xProject/0x-mesh/pull/300. @dekz can you try running a development version and see if that fixes the issue. I'll send you the details privately.

**Comment by dekz** [comment]
@albrow I haven't seen the error occur since updating to the dev branch or on 2.0.0

**Comment by dekz** [comment]
This started to re-appear on 3.0.1-beta

![image](https://user-images.githubusercontent.com/27389/63131742-18336600-c002-11e9-9db6-7757966f9a66.png)
