### ISSUE TITLE
Remove `mesh_addPeers` endpoint

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#321]
We initially added a JSON-RPC endpoint to manually add peers. Now that we've implemented peer discovery, we should remove this endpoint.

**Comment by albrow** [comment]
I still think it is useful for testing with different network topologies and can help us track down the issues we were seeing with failing to fall back to a relay connection.

**Comment by fabioberger** [comment]
Ok, let's keep it then.
