### ISSUE TITLE
Broken link on the USAGE.md page

### ISSUE THREAD

**Issue by labsterx** [0xProject/0x-mesh#338]
On this page: https://github.com/0xProject/0x-mesh/blob/development/docs/USAGE.md, the link "Typescript RPC client" (Under the "Recommended Clients:" section) is a broken link. The target URL  https://github.com/0xProject/0x-mesh/blob/development/docs/docs/json_rpc_clients/typescript/README.md returns a 404 error.

**Comment by albrow** [comment]
Thanks for the heads up. Should be fixed in #340.
