### ISSUE TITLE
blockwatch: Encode block param without leading zeros

### ISSUE THREAD

**Issue by yondonfu** [0xProject/0x-mesh#342]
`(*RpcClient).HeaderByNumber()` encodes the provided number with the [common.Bytes2Hex()](https://github.com/0xProject/0x-mesh/blob/development/ethereum/blockwatch/client.go#L64) helper. This helper will produce hex string representations for certain numbers that will be considered invalid by the [Ethereum JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) due to leading zeros following the `0x` prefix. This seems to be a problem at least when sending requests to geth.

Example code:

```go
num := big.NewInt(271)
fmt.Printf("%v\n", fmt.Sprintf("0x%s", common.Bytes2Hex(num.Bytes())))
fmt.Printf("%v\n", hexutil.EncodeBig(num))

num = big.NewInt(6000000)
fmt.Printf("%v\n", fmt.Sprintf("0x%s", common.Bytes2Hex(num.Bytes())))
fmt.Printf("%v\n", hexutil.EncodeBig(num))
```

And the output:

```
0x010f
0x10f
0x5b8d80
0x5b8d80
```

Note that in the first example of the code snippet that `hexutil.EncodeBig()` produces a valid output while `common.Bytes2Hex()` does not.

**Comment by fabioberger** [comment]
Thanks for the report @yondonfu, will address this today.
