### ISSUE TITLE
core: Delete random orders when DB is full

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#373]
If the DB is full, the simplest thing we can do is remove random orders to make space for incoming orders. We will start there and then eventually replace this with a more robust solution.

**Comment by fabioberger** [comment]
Spoke about this offline and decided that the best approach is actually to delete the orders with the oldest `lastUpdated` times. `lastUpdated` times can be seen as a proxy of the orders usefulness since better orders are more likely to get filled as time goes on.

**Comment by albrow** [comment]
Closing in favor of #450.
