### ISSUE TITLE
Mesh Node Dies

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-mesh#377]
What is the expected uptime for a mesh node? Ours seems to die after 8 hours. We are running the latest from DockerHub on a VM with 1 Gig ram. Thoughts?

**Comment by albrow** [comment]
@pointtoken Mesh should be able to run indefinitely and we have some nodes with an uptime of over 2 weeks.

Can you share more information so we can help debug any possible issues? Do you see any errors in the logs?

**Comment by pointtoken** [comment]
We've been up 25 hours to date, so maybe it was a bug in an earlier build. Where would we find the log files? We are running detached with verbosity = 1

**Comment by albrow** [comment]
Mesh just outputs logs to stdout, so you can use [`docker logs`](https://docs.docker.com/engine/reference/commandline/logs/). The exact command depends on how you have Docker setup, but it's usually just:

```
docker logs <container name>
```

**Comment by pointtoken** [comment]
thanks. bug seems to be fixed in the latest version.

**Comment by pointtoken** [comment]
I'm reopening this as our node died after about 4 days. @albrow  how does one get at the logs from a container that no longer exists?

**Comment by albrow** [comment]
@pointtoken can you share more information about your setup?

- What version of Mesh are you running?
- How are you running it? What Docker command?
- Where is the container hosted?

If `docker logs` doesn't show anything then that means the container itself was stopped. Unfortunately there is no way to read from stdout for a container that is no longer running. This is a limitation of Docker.

For our own infrastructure, we pipe all logs to Elasticsearch and Kiabana so we always have a way to search them even if the Docker container is not running. If you want, you can opt-in to send us your logs by [following this guide](https://0x-org.gitbook.io/mesh/getting-started/beta_telemetry_node) then we could help you debug any potential issues.

Alternatively you could use a simple bash script to redirect the output from Docker to a file. E.g., something like:

```bash
# Don't forget to include any needed environment variables.
docker run 0xorg/mesh:3.0.1-beta > /file/on/host/machine
```

**Comment by pointtoken** [comment]
It is running in an EC2 container. Here's the command used:

```
docker run -it --rm -d -p 60557:60557 -p 60558:60558 -e ETHEREUM_NETWORK_ID="1" -e ETHEREUM_RPC_URL="https://mainnet.infura.io/v3/XXX" -e  VERBOSITY=2 -v /home/ec2-user/0x_mesh:/usr/mesh/0x_mesh 0xorg/mesh:latest > /home/ec2-user/mesh-logs/log.txt
```
Running the latest image that's been pushed to DockerHub. 

Seems to die after about 48 hours.

**Comment by albrow** [comment]
Possibly related: #452.

**Comment by albrow** [comment]
@pointtoken we haven't heard from you in two months, so I'm closing this issue for now. If you are still having problems and are able to share any additional information, I'd be happy to re-open it.
