### ISSUE TITLE
Broken links on Mesh guide

### ISSUE THREAD

**Issue by fulviamorales** [0xProject/0x-mesh#424]
Some links on the Mesh guide are broken. Below is a list of the ones I found: 

On `Mesh Beta Participation` tab:
`JSON-RPC API Documentation`

On `JSON-RPC-API Documentation` tab:
`demos`

On `Browser guide` tab:
`The examples/browser directory`

On `Syncing an external DB with Mesh` tab:
`Mesh Typescript client`, `getOrders`, `onReconnected`

After talking to Alex B. it looks like GitBook generates those webpages from Markdown files in the 0x-mesh GitHub repo and that there are some mistakes in the Markdown source.

**Comment by albrow** [comment]
Fixed via https://github.com/0xProject/0x-mesh/pull/429
