### ISSUE TITLE
Add support for custom Ethereum networks

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#435]
While we do provide a Ganache snapshot and corresponding Docker image, there is currently no way for developers to use their own custom Ethereum network for testing. This makes it harder for those who can't or don't want to use Ganache.

We can add support for custom Ethereum networks via an environment variable/config option. The main thing we would need is the addresses of relevant smart contracts on that network.

**Comment by fabioberger** [comment]
Fixed in #445
