### ISSUE TITLE
orderwatch: Delete `removed` orders from DB more frequently

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#459]
Currently we re-evaluate whether to remove an order that has been flagged for removal from the DB during the cleanup job (runs every hour) or if an event triggers the orders revalidation. We feel the 1hr interval between cleanup jobs is too long and can cause the DB to be full of `removed` orders. We should delete `removed` orders after ~5min (the time it takes for a block re-org to become highly unlikely). We can do this, by checking `removed` orders if ~5min have passed in a separate loop every ~5min.

**Comment by albrow** [comment]
Fixed by https://github.com/0xProject/0x-mesh/pull/471
