### ISSUE TITLE
blockwatch: Don't fast-sync if more than 128 blocks behind

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#470]
Currently, we always fast-sync when a Mesh node is behind the latest block. If it is far behind, it can take up quite some memory (see: #407). In addition, if we are more than 128 blocks behind, the resultant order revalidations would require a backing Ethereum node with `archive` mode enabled. Most do not have this.

Instead, if Mesh is more than 128 blocks behind, we should simply revalidate all orders once and re-set the latest block in the DB to the current head of the chain.

**Comment by dekz** [comment]
~32 minutes for 128 blocks isn't a huge outage. Network blip, infura/alchemy down aren't rare.

If mesh blows past all of the blocks during that outage, what will a Market Maker see in terms of book keeping? Will they get a bunch of `EXPIRED` updated where some of them should have `FILLED` events on them? How does this effect a Market Makers book keeping and audit history?

For a "relayer" this is the right approach, unless they too were showing a users history.
