### ISSUE TITLE
Support passing in a web3 provider in the browser

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#581]
Currently, when running Mesh in the browser, you need to provide an Ethereum RPC URL. This works great for some applications but isn't ideal for others. For example, it may expose your Infura/Alchemy API key and lead to abuse.

Most of the 0x TypeScript tooling supports [passing in a web3 provider](https://0x.org/docs/guides/web3-provider-explained), which can be provided by a wallet. We should support this use case when running Mesh in the browser.

The biggest challenge here will be passing the provider through to the Wasm bytecode and making it work correctly with `go-ethereum` and our generated Go contract wrappers.

**Comment by joeykrug** [comment]
status of this? we need this for launch

**Comment by albrow** [comment]
@joeykrug Thanks for letting us know. In terms of new features, we're currently working on #576 and #577. Plan is to work on this afterwards.

**Comment by albrow** [comment]
@joeykrug this was implemented in https://github.com/0xProject/0x-mesh/pull/665 and will be included in version 9.0.0.
