### ISSUE TITLE
meshdb,core: Check if DB has V2 or V3 orders stored on startup

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#607]
Currently, we disallow an operator from re-starting their Mesh node with a different chainID then on previous startup without first wiping their database. This prevents the node from trying to validate/share Kovan orders as mainnet orders.

We don't do the same thing for a Mesh node previously started for 0x V2 orders, and then re-started for V3. This can cause the Mesh node to attempt validating V2 orders as if they are V3 orders. 

This leads to the:

```
validationResults.Rejected contained unknown order hash
```

error where the order fails signature validation because we attempt to validate a previously stored V2 order with the V3 smart contract and it obviously fails this validation. The reason Mesh fails to find this order in the `knownOrderHashes` mapping is because `chainID` is not stored as part of the order in V2, and so gets set to the default `0` value, causing the orderHash computed to be different from the orderHash stored in the DB.

We could solve this issue but with the impending deprecation of V2, it might not be worth the effort. Developers should be made aware that they must clear their DB between running the V2 and V3 versions of Mesh.

**Comment by albrow** [comment]
This is likely related to https://github.com/0xProject/0x-mesh/issues/583 and https://github.com/0xProject/0x-mesh/issues/537.

**Comment by fabioberger** [comment]
Probably no longer worthwhile given that we're no longer supporting both versions actively.
