### ISSUE TITLE
zeroex: Upgrade to OrderValidator contract with signature validation

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#62]
Currently the `getOrderInfosAndTraderInfos` method in the `OrderValidator` library we are using doesn't validate signatures. We should upgrade to a contract that does.

**Comment by albrow** [comment]
@fabioberger I believe this was done in #76?

**Comment by fabioberger** [comment]
Closed by: https://github.com/0xProject/0x-mesh/pull/76
