### ISSUE TITLE
Mesh says loading on startup

### ISSUE THREAD

**Issue by joeykrug** [0xProject/0x-mesh#627]
```
git clone https://github.com/AugurProject/augur.git
yarn clean
 yarn 
yarn build
 yarn docker:all true  
yarn build -w
 yarn workspace @augurproject/ui dev
  yarn flash run create-reasonable-yes-no-market
```

Says Error: Mesh is still loading. Try again soon.

https://cdn.discordapp.com/attachments/378030793899114516/664180753440964657/unknown.png

**Comment by albrow** [comment]
This happens when you call `addOrdersAsync` before the Wasm bytecode is done loading. This should be relatively easy to fix. We just need to allow calls to `addOrdersAsync` while the Wasm bytecode is still loading (by simply blocking until it is ready).

In the meantime, as a workaround, you can just wait and try calling `addOrdersAsync` again after 5-10s.

**Comment by bthaile** [comment]
I got past this issue by waiting between the time UI connected to mesh and navigating to a market to create an order. I'll keep up this workflow and will comment again if needed. thanks

**Comment by albrow** [comment]
Thanks @bthaile. To be clear, it is something we plan to address. So hopefully soon you will be able to remove that workaround.

**Comment by joeykrug** [comment]
I think mesh gets stuck loading sometimes too, like it’ll say this forever. If I refresh and retry it’ll usually successfully reload. But it’s getting stuck somehow and loading indefinitely sometimes when this happens

**Comment by joeykrug** [comment]
yep confirmed it'll say that indefinitely unless I refresh

**Comment by albrow** [comment]
@joeykrug are you sure you're calling `startAsync` before anything else? Are there any other errors in the console?

I followed the steps you shared above and did not see the `Mesh is still loading. Try again soon.` error at all. Is there any other information you can share about what you are doing to trigger this?

**Comment by joeykrug** [comment]
figured it out, it's an error when we have leftover mesh state and are doing a new contract deploy.. on our side
