### ISSUE TITLE
Feature request : local mode

### ISSUE THREAD

**Issue by SvenMeyer** [0xProject/0x-mesh#657]
# Context

I am running a 0x-lauch-kit backend with mesh 7-0xv3 for development purposes, and alpha testnet deployment.

# Current Behavior

Fabio already pointed out that running it on AWS might become quite expensive.
I checked myself and could confirm that ~3000 GB/month incoming as well as ~3000 GB/month outgoing traffic are being used.

After mapping ports 60558 and 60559 of the mesh container to 'nirvana' (11111 and 22222) it looks like as if the traffic goes down to "only" ~ 1600 GB/month - which is still too much.

# Expected Behavior

Now that 0x backend does not work any more without mesh, because mesh is verifying the orders, just switching off mesh to get a "local mode" is not an option any more.

I would like to request a "Local Mode" option, so that mesh only communicates with the (local) backend, verifies the orders, but does not accept any incoming, nor initiates any outgoing communication.

Local mode comes especially handy during development when:
- you want to keep communication cost down
- you want to make sure that nobody adds or removes any orders which you may create for testing and verification purpose
- you want to make sure that everything happening on your exchange, happens because of actions you initiated
- I know that normally, we would like to have as much liquidity as possible, but even in live mode, there might be reasons why you want to launch your exchange relayer in local mode (to start with), i.e. you only want early adopter to use and test it first.

**Comment by albrow** [comment]
@SvenMeyer I think what you want is already achievable by setting `USE_BOOTSTRAP_LIST=false`. This will make it so that Mesh will not connect to, receive orders from, or share orders with other peers in the network. You can still use Mesh to validate and watch any orders that you add.

**Comment by SvenMeyer** [comment]
@albrow thanks, really looks like exactly what I was looking for. I will give it a try!

**Comment by SvenMeyer** [comment]
@albrow That really made the difference. Traffic now to more or less zero!
