### ISSUE TITLE
RPC Connectionn to Mesh Node that uses Infura Hosted Node

### ISSUE THREAD

**Issue by SupahAmbition** [0xProject/0x-mesh#668]
I'm new to 0x so if this is on my end, apologies in advance, but I haven't been able to figure it out.

- I am running the Mesh Node inside docker. (Ubuntu Linux,  18.10) 
Here is the command i use to setup the node. I haven't set any other environment variables. 
I've censored out the end of my infura link. 
``` 
docker run
--restart unless-stopped
-p 60557:60557 
-p 60558:60558 
-p 60559:60559 
-e ETHEREUM_CHAIN_ID="1" 
-e ETHEREUM_RPC_URL="https://mainnet.infura.io/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
-e VERBOSITY=5 
-v $(pwd)/0x_mesh:/usr/mesh/0x_mesh 0xorg/mesh:latest
```

- What version of Mesh are you running? 8.1.2 (up to date with the master branch) 
- Are you using an RPC client and if so, which one? Golang client 

# Expected Behavior

This Bit of code that just connects the go RPC client to the local mesh node should work.
```
import (zerox "github.com/0xProject/0x-mesh/rpc")
c, dial := zerox.NewClient("ws://localhost:60557")
if dial != nil {
         log.Fatal(dial)
}
```

Please describe the behavior you are expecting.

# Current Behavior
program fails with: 
`read tcp 127.0.0.1:33084->127.0.0.1:60557: read: connection reset by peer`

## Failure Logs

Please include any relevant log snippets or files here.
I see the log entries for starting the RPC server, order watcher, block watcher, 
and the log entries for PRC server started, and core app started. 
Then everything seems to work just fine. If there is something else I should be looking for in the logs then let me know.

**Comment by fabioberger** [comment]
@SupahAmbition please try adding the follow env var on Mesh startup: 

```
-e RPC_ADDR=0.0.0.0:60557
```

The default RPC_ADDR is set to `localhost:60557` but I don't think that plays nicely with Mesh when it's dockerized.

**Comment by SupahAmbition** [comment]
@fabioberger That worked! Thank you for quick response.
