### ISSUE TITLE
Mixed Content error when running Mesh in browser on an HTTPS domain

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#674]
## Context

Running Mesh in the browser. Any version <= 8.1.2.

## Expected Behavior

Mesh should work when hosted on an HTTPS domain. Most application developers using Mesh in production will need to use HTTPS for security reasons.

## Current Behavior

Attempting to run Mesh in the browser on an HTTPS domain results in the following error every time that you try to dial a new peer:

```
Mixed Content: The page at '<URL that Mesh is hosted on>' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint '<peer you were trying to dial>'. This request has been blocked; this endpoint must be available over WSS.
```

The exact error message depends on your browser, but AFAIK there are no browsers that support dialing WS URLs from an HTTPS domain. You need to use WSS.

## How to address/fix

Our near term plan for addressing this is:

- [ ] Add support for dialing WSS to https://github.com/libp2p/go-ws-transport
- [ ] Add SSL certificates and a proxy (e.g. nginx) for all of our bootstrap nodes and relay nodes. Each node will also need a unique domain name (or a unique subdomain on a shared domain name).
- [ ] Update our bootstrap nodes relay nodes to advertise these new domain names.
- [ ] Update the default bootstrap list in Mesh to include these new domain names.

**Comment by albrow** [comment]
PR is open at https://github.com/libp2p/go-ws-transport/pull/72, but it needs a little bit more work before it's ready. Waiting on feedback.

**Comment by pgebheim** [comment]
I am experiencing this as well, in my case it causes the Go program in the WebASM runtime to die.

![image](https://user-images.githubusercontent.com/86010/73148106-5df36080-406f-11ea-807d-5805d4727f24.png)

**Comment by albrow** [comment]
Fixed in https://github.com/0xProject/0x-mesh/pull/696. Starting with version `9.0.0` Mesh has support for dialing over WSS.
