### ISSUE TITLE
examples: Browser example fails to run

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#675]
# Context

- Development branch (commit: 2e7a2027bf2a101a00d87ff05c12cf0a171f68a6)
- Running the browser example

# Expected Behavior

The example works.

# Current Behavior

Browser Mesh crashes.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Checkout `development`
2. `cd browser; yarn; yarn build`
3. `cd ../examples/browser; yarn install --force; yarn build; `
4. Open browser to `localhost:8000`

## Failure Logs

Please include any relevant log snippets or files here.

```
panic: syscall/js: Value.Call: property _makeFuncWrapper is not a function, got undefined wasm_exec.js:97:29
<empty string> wasm_exec.js:97:29
goroutine 1 [running]: wasm_exec.js:97:29
syscall/js.Value.Call(0x7ff8000000000007, 0x219857, 0x10, 0xc263f20, 0x1, 0x1, 0xc085180) wasm_exec.js:97:29
	/usr/local/opt/go/libexec/src/syscall/js/js.go:299 +0x87 wasm_exec.js:97:29
syscall/js.FuncOf(0x37ea88, 0x23839a, 0x32) wasm_exec.js:97:29
	/usr/local/opt/go/libexec/src/syscall/js/func.go:46 +0xa wasm_exec.js:97:29
main.setGlobals() wasm_exec.js:97:29
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:43 +0x2 wasm_exec.js:97:29
main.main() wasm_exec.js:97:29
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:30 +0x1 wasm_exec.js:97:29
exit code: 2 wasm_exec.js:156:29
```

**Comment by albrow** [comment]
@fabioberger I can't reproduce this. The browser example works for me on `development`. I think you just need to use Go 1.13.

**Comment by fabioberger** [comment]
Yep, good catch. I was compiling with Go 1.12.
