### ISSUE TITLE
browser: Mesh crashes on Safari

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#682]
# Context

Please provide any relevant information about your setup

- Mesh 8.2.0 in the browser
- Safari v13.0.4

# Expected Behavior

Mesh runs normally

# Current Behavior

Mesh crashes with a `Maximum call stack size exceeded` error.

# Failure Information (for bugs)

## Failure Logs

<img width="519" alt="Screen_Shot_2020-01-28_at_11 58 40_AM" src="https://user-images.githubusercontent.com/2151492/73337244-38837400-4274-11ea-8ff5-c14ae21562d5.png">

- https://github.com/mono/mono/issues/15981
- https://bugs.webkit.org/show_bug.cgi?id=201028
- https://bugs.webkit.org/show_bug.cgi?id=201026
- https://www.gitmemory.com/issue/mono/mono/16986/535938327
- https://github.com/jaykrell/mono/commit/47d755703ddf6d3b704cb2be64e943a45eaa51da
- https://github.com/golang/go/issues/34664
- also note this https://github.com/golang/go/issues/35111 go 1.14 fixes a memory leak
- this issue is happening here somehow https://github.com/0xProject/0x-mesh/blob/master/browser/ts/wasm_exec.ts#L391

31713 is call stack limit in safari, but in chrome it's 15676. So it's almost as if it's entering an infinite loop/recursion in safari somehow

**Comment by joeykrug** [comment]
Works with https://bugs.webkit.org/show_bug.cgi?id=206436, should be fixed in next Safari release

**Comment by joeykrug** [comment]
Doesn't actually work, occurs about 50% of the time, so I spoke to soon. Try Safari Technology Preview to see it

**Comment by joeykrug** [comment]
Safari preview 100 fixes it for good
