### ISSUE TITLE
Error using standalone mesh server as bootstrap node with browser mesh

### ISSUE THREAD

**Issue by nuevoalex** [0xProject/0x-mesh#688]
# Context

Running both mesh in the browser and as a standalone server from Docker where we are using the typescript RPC client to communicate with it.

Versions:

```
@0x/mesh-browser: 8.2.0
@0x/mesh-rpc-client: 8.1.2
0xorg/mesh: 8.1.2
```

# Expected Behavior

The browser mesh establishes a connection with the standalone server as a bootstrap node without error and events are transmitted between them.

# Current Behavior

When the browser mesh is starting up I receive this error message:

```
{
  "error_string": "failed to dial : all dials failed\n  * [/ip4/127.0.0.1/tcp/60559/ws] failed to negotiate security protocol: connected to wrong peer",
  "level": "warning",
  "msg": "failed to connect to bootstrap peer",
  "myPeerID": "16Uiu2HAmS4BGNxYVMDSsn3eoScLsB6BzGBfuN3asGimkGZWQZye6",
  "peerInfo_json_string": "{\"Addrs\":[\"/ip4/127.0.0.1/tcp/60558\",\"/ip4/127.0.0.1/tcp/60559/ws\"],\"ID\":\"16Uiu2HAmRMgvPQV2UYKXuuCnNaFLpc36PhLp2UKVcL1ePseVcz4y\"}",
  "time": "2020-01-29T22:41:33-08:00"
}
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start the mesh docker with this configuration:
```
'-p', '60557:60557', // rpc_port_number
'-p', '60558:60558', // P2PTCPPort
'-p', '60559:60559', // P2PWebSocketsPort
'-e', `ETHEREUM_CHAIN_ID=${networkId}`,
'-e', `ETHEREUM_RPC_URL=${ethNode}`,
'-e', 'USE_BOOTSTRAP_LIST=false',
'-e', 'BLOCK_POLLING_INTERVAL=1s',
'-e', 'ETHEREUM_RPC_MAX_REQUESTS_PER_24_HR_UTC=169120', // needed when polling interval is 1s
'-e', `CUSTOM_CONTRACT_ADDRESSES=${JSON.stringify(addresses)}`,
'-e', 'VERBOSITY=4', // 5=debug 6=trace
'-e', 'RPC_ADDR=0x:60557', // need to use "0x" network
```
2. Start the browser mesh instance with this bootstrap list:
```
"bootstrapList": [ "/ip4/127.0.0.1/tcp/60558/ipfs/16Uiu2HAmRMgvPQV2UYKXuuCnNaFLpc36PhLp2UKVcL1ePseVcz4y",
  "/ip4/127.0.0.1/tcp/60559/ws/ipfs/16Uiu2HAmRMgvPQV2UYKXuuCnNaFLpc36PhLp2UKVcL1ePseVcz4y"
]
```

**Comment by fabioberger** [comment]
@nuevoalex Are you unable to connect to the bootstrap node from _both_ the browser-based Mesh node _and_ the TS RPC Client?

**Comment by nuevoalex** [comment]
@fabioberger yes

**Comment by albrow** [comment]
@nuevoalex `failed to negotiate security protocol: connected to wrong peer` likely means that your bootstrap list has the wrong peer ID for your bootstrap node. Can you double check that your bootstrap node actually has a peer ID of `16Uiu2HAmRMgvPQV2UYKXuuCnNaFLpc36PhLp2UKVcL1ePseVcz4y`?

**Comment by albrow** [comment]
Also you should probably be using `0xorg/mesh-bootstrap` as the image for your bootstrap node. `0xorg/mesh` might technically work but it's not designed to be a bootstrap node. For example, it will not be able to establish a relay connection between peers and might have other smaller issues.

**Comment by albrow** [comment]
@nuevoalex are you still having this problem or can we close this issue?

**Comment by nuevoalex** [comment]
@albrow Ah sorry, forgot to update here. This can be closed, thanks!
