### ISSUE TITLE
Run our own bootstrap nodes

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#75]
Depends on https://github.com/0xProject/0x-mesh/issues/72.

We should use our own list for bootstrapping the DHT. In #69 we use the default IPFS bootstrap list.

**Comment by fabioberger** [comment]
Just want to add that we probably want to deploy bootstrap nodes for every network we support (e.g., mainnet, Kovan, Ropsten & Rinkeby).

**Comment by albrow** [comment]
Fixed via https://github.com/0xProject/0x-mesh/pull/235, https://github.com/0xProject/0x-mesh/pull/243, and https://github.com/0xProject/0x-mesh/pull/247.
