### ISSUE TITLE
Error in browser: corruption on table-footer

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#801]
# Context

Augur reported the following issue on Discord:

![](https://media.discordapp.net/attachments/518207682470084618/704374340082466816/unknown.png)

> I'm assuming this is because IDB doesn't have write guarnatees, so writing the leveldb blob probably failed
> and then that died
> The only thing to do in response to that error is to delete the databse and remake it I think
> Currently I think we'd n eed to delete the DB and then refresh
> Also, that error doesn't get sent to the onError handler so we can't handle it

Please provide any relevant information about your setup

- Are you running Mesh in the browser or as a standalone server? Are running Mesh inside of Docker or directly running the binary?

In the browser. Chrome Version 81.0.4044.129 (Offcial Build) (64-bit)

@pgebheim which browser? Which mobile device or OS?

- What version of Mesh are you running? Be as specific as possible (e.g., `8.0.1` instead of `latest` or `8`).

9.2.1 at time of crash.

# Expected Behavior

Mesh should not crash when reading/writing from IndexedDB

# Current Behavior

What is the current behavior?

Mesh appears to crash.

# Failure Information (for bugs)

(See screenshot and comment above)

## Steps to Reproduce

@pgebheim can you answer this? If you don't have exact steps to reproduce, maybe you can describe what were you doing when you saw this error?

## Failure Logs

(See screenshot above)

**Comment by pgebheim** [comment]
I'll gather some information here, we've only encountered it once -- and it was on Chrome w/ windows 10.

**Comment by albrow** [comment]
Since we are using a different database implementation for v10, I think we can safely close this.
