### ISSUE TITLE
Error when using custom provider: Cannot destructure 'method' of 'item.params'

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#804]
# Context

Augur reported this issue on Discord.

- Are you running Mesh in the browser or as a standalone server? Are running Mesh inside of Docker or directly running the binary?

In the browser.

- What version of Mesh are you running? Be as specific as possible (e.g., `8.0.1` instead of `latest` or `8`).

@pgebheim can you answer this? It sounds like maybe this is on version 9.3.0?

# Expected Behavior

Mesh should work with custom providers, as long as they implement the correct interface.

# Current Behavior

Mesh throws an error when using custom providers.

# Failure Information (for bugs)

> btw after upgrading I am getting errors in our provider

![](https://cdn.discordapp.com/attachments/518207682470084618/706971119168520242/unknown.png)

![](https://cdn.discordapp.com/attachments/518207682470084618/706972476441362572/unknown.png)

> eth_chainId doesn't have params...
> that must be it
> yeup
> btw, eth_chainId isn't a thing
> https://ethereum-magicians.org/t/eip-695-create-eth-chainid-method-for-json-rpc/1845/20
>  its in EIP and latest discussion is people saying to move it back to draft
> and the return value isn't decided on yet
> heh

## Steps to Reproduce

@pgebheim can you answer this? Can you provide more information about how you are setting up your provider so that we can try and reproduce? We know that it works in our example in the Mesh repository, which uses Metamask as the Provider.

## Failure Logs

(See screenshots above).

**Comment by pgebheim** [comment]
Our middleware assumes that the params key on the json-rpc payload is always defined. The call mesh is doing for eth_chainId doesn't include the params key and was causing an error.

Patched here: https://github.com/AugurProject/augur/blob/8b22ae899d660243a8fe0f9000230073c7699456/packages/ethersjs-provider/src/EthersProvider.ts#L80

I believe you should always pass params with these eth calls, but this is also an oversight in our code.

Also, take it under advisement that this is not yet included in ethereum officially as it's still an EIP that is under debate.

**Comment by albrow** [comment]
@pgebheim thanks. We have so far tested on Alchemy, Infura, and Metamask. We'll try and stay tuned in on the discussion around the EIP and update things on our end as needed.

Is it safe to close this issue now?

**Comment by pgebheim** [comment]
Definitely

Paul

________________________________
