### ISSUE TITLE
Safari using multiple gigabytes for 0x-mesh-db

### ISSUE THREAD

**Issue by pgebheim** [0xProject/0x-mesh#807]
# Context

Please provide any relevant information about your setup

- Mesh in browser
   - Safari under iOS 13.3.1
   - Safari Developer Preview under MacOS

# Expected Behavior

`0x-mesh-db` should be relatively small for instance in chrome we're seeing < 1mb

# Current Behavior

In safari, the DB size grows to multiple gigabytes, although it appears to prune itself somewhere around ~3.6gb of usage.

# Failure Information (for bugs)

Looking at the logs, it seems as if we sync 4345 distinct orders from 2 peers. There's various log messages about websockets not connecting (normal), but not seeing a lot that looks out of place.

## Steps to Reproduce
- Visit v2.augur.net in safari.
- Wait
- You will start getting popups asking to increase disk usage

## Failure Logs
- [console-logs.txt](https://github.com/0xProject/0x-mesh/files/4624786/console-logs.txt)
- Database sent via google drive link

**Comment by albrow** [comment]
I quickly tested this using the new code from https://github.com/0xProject/0x-mesh/pull/793. This no longer appears to be an issue. After https://github.com/0xProject/0x-mesh/pull/793 is merged we can probably close this.

**Comment by pgebheim** [comment]
That's awesome! Will reopen if we see it again.
