### ISSUE TITLE
cannot call non-function event.ID

### ISSUE THREAD

**Issue by xiao0811** [0xProject/0x-mesh#816]
go run ./examples/go/subscribe-to-orders/main.go
![image](https://user-images.githubusercontent.com/24801940/83476917-7ca5b000-a4c4-11ea-8446-02e7581ae6a8.png)

**Comment by albrow** [comment]
@xiao0811 I just tested this in the `development` branch and it works fine. I can see from the logs that you are using Mesh version `7.1.0-beta` which is about 5 months old. Please upgrade to the latest version and try again. Let me know if you are seeing any issues.

**Comment by xiao0811** [comment]
@albrow Thanks, I will upgrade
