### ISSUE TITLE
chainId must be specified according to EIP-155

### ISSUE THREAD

**Issue by xiao0811** [0xProject/0x-mesh#828]
https://github.com/0xProject/0x-mesh/blob/ee19434329a3b629edf037fef493cfc16a20afd8/examples/go/add-order/main.go#L32

```go
// Order represents an unsigned 0x order
type Order struct {
	MakerAddress          common.Address `json:"makerAddress"`
	MakerAssetData        []byte         `json:"makerAssetData"`
	MakerAssetAmount      *big.Int       `json:"makerAssetAmount"`
	MakerFee              *big.Int       `json:"makerFee"`
	TakerAddress          common.Address `json:"takerAddress"`
	TakerAssetData        []byte         `json:"takerAssetData"`
	TakerAssetAmount      *big.Int       `json:"takerAssetAmount"`
	TakerFee              *big.Int       `json:"takerFee"`
	SenderAddress         common.Address `json:"senderAddress"`
	ExchangeAddress       common.Address `json:"exchangeAddress"`
	FeeRecipientAddress   common.Address `json:"feeRecipientAddress"`
	ExpirationTimeSeconds *big.Int       `json:"expirationTimeSeconds"`
	Salt                  *big.Int       `json:"salt"`

	// Cache hash for performance
	hash *common.Hash
}
```
There is no ChainID in the Order struct

**Comment by xiao0811** [comment]
Run `0x-mesh/examples/go/add-order/main.go`
`zeroex.Order` in `0x-mesh/zeroex/order.go`
```bash
FATA[0000] could not sign 0x order                       error="chainId must be specified according to EIP-155"
```

**Comment by jalextowle** [comment]
@xiao0811 Could you elaborate on the issue that you see here, and let us know whether or not my answer was satisfactory?

**Comment by xiao0811** [comment]
Thank you for your kind help
We are going to make a decentralized exchange, but now we don’t have much experience. I have only done a little Ethereum development before. Can you tell me what I need to do to build 0x

**Comment by jalextowle** [comment]
@xiao0811 Can you join our discord https://twitter.com/0xProject/status/1091126664300453888?s=20? I think that platform would be better suited to discussions like this than Github issues.

I can't meaningfully answer your question because I'm not sure what you mean by "what I need to do to build 0x." Please join our Discord and elaborate on what guidance you are looking for in our #general-help channel.

**Comment by xiao0811** [comment]
@jalextowle Thank you
