### ISSUE TITLE
The method eth_sign does not exist/is not available

### ISSUE THREAD

**Issue by xiao0811** [0xProject/0x-mesh#838]
run test TestEthRPCSigner
https://github.com/0xProject/0x-mesh/blob/ee19434329a3b629edf037fef493cfc16a20afd8/ethereum/signer/sign_test.go#L15

```bash
--- FAIL: TestEthRPCSigner (1.43s)
    sign_test.go:29: 
        	Error Trace:	sign_test.go:29
        	Error:      	Received unexpected error:
        	            	The method eth_sign does not exist/is not available
        	Test:       	TestEthRPCSigner
FAIL
FAIL	github.com/0xProject/0x-mesh/ethereum/signer	1.465s
FAIL
```

**Comment by xiao0811** [comment]
https://github.com/0xProject/0x-mesh/blob/ee19434329a3b629edf037fef493cfc16a20afd8/constants/constants.go#L22
GanacheEndpoint

**Comment by xiao0811** [comment]
https://github.com/0xProject/0x-mesh/blob/ee19434329a3b629edf037fef493cfc16a20afd8/constants/constants.go#L22
GanacheEndpoint

**Comment by xiao0811** [comment]
Also, how do I get `0x-api-key`

**Comment by albrow** [comment]
@xiao0811 are you following the [Contribution Guide](https://github.com/0xProject/0x-mesh/blob/master/CONTRIBUTING.md)? The test passes for me and passes on CI. I think this might just be a problem with your development setup.

**Comment by albrow** [comment]
> Also, how do I get `0x-api-key`

`0x-api-key` is not required for using Mesh. Maybe this is a question for [the 0x API channel on Discord](https://discord.com/channels/435912040142602260/667077687860527125)?

**Comment by xiao0811** [comment]
@albrow Thank you, our company is considering making a decentralized exchange, so we found this. But we are not very professional. We have some problems in setting up the test environment.
Can you tell me how to build a decentralized exchange
thanks again.

**Comment by xiao0811** [comment]
There are so many projects on your github, which ones should I choose to build our application.

**Comment by albrow** [comment]
@xiao0811 this repository is specifically for 0x Mesh, which is just one small part of the 0x tech stack. We're happy to help you, but I think the best way to do this would be to [post a question in our Discord](https://discord.com/channels/435912040142602260/436256771175088148).

Is the original problem that you posted "The method eth_sign does not exist/is not available" solved now? And if so can I mark this issue as resolved?

**Comment by xiao0811** [comment]
@albrow ok
