### ISSUE TITLE
core: Add config flag to disable p2p-networking

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#95]
Some developers might want to use Mesh as a replacement for [0xorg/order-watcher](https://cloud.docker.com/u/0xorg/repository/docker/0xorg/order-watcher) and for that use-case, the p2p networking isn't required.

This is also useful when stress-testing the order-watching functionality of the 0x Mesh node.

**Comment by albrow** [comment]
@fabioberger would it be better to just split off this new version of order watcher into a separate executable/docker container?

**Comment by fabioberger** [comment]
Alex and I discussed this off-line and since we eventually want to remove this flag and have developers using Mesh's order-watching functionality to also pull orders from the Mesh network, it makes sense to implement this as a temporary flag we will deprecate in a future release.

**Comment by fabioberger** [comment]
After more thought, this isn't worth the effort.
